source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/myiOSComponent/myRepo.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'TKModelCategory_Example' do
  pod 'TKModelCategory', :path => '../'

  target 'TKModelCategory_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
