use_frameworks!

target 'TKModelCategory_Example' do
  pod 'TKModelCategory', :path => '../'

  target 'TKModelCategory_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
